# Generated by Django 3.1.1 on 2020-10-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='start',
            new_name='starts',
        ),
    ]
