# Generated by Django 3.1.1 on 2020-10-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20201006_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='starts',
            new_name='stars',
        ),
    ]
