# Generated by Django 3.1.1 on 2020-10-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_category_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='featured',
            new_name='feature',
        ),
    ]
