# Generated by Django 3.1.1 on 2020-10-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20201008_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.FloatField(default=0.0),
        ),
    ]
